application:
  basePath: ${PROJECT_BASE_PATH:/${user.home}/project-rest}
server:
  port: 0
spring:
  application:
    name: ProjectRestPublicEndpoint
  profiles:
    include: kafka, zookeeper, rest, mongodb
