application:
  basePath: ${PROJECT_BASE_PATH:/${user.home}/xls2rdf-rest}
server:
  port: 0
spring:
  application:
    name: Xls2RdfRestPublicEndpoint
  profiles:
    include: kafka, zookeeper, rest, feign
logging:
  level.*: INFO
  config: classpath:logback.xml
  file:
    path: ${application.basePath}/logs