server:
  port: 8088
spring:
  profiles:
    include: kafka,virtuoso,elasticsearch,zuul
  kafka:
    template:
      default-topic: event-sink-rest

elasticsearch:
  index: movies

management:
  health:
    elasticsearch:
      enabled: false
