zuul:
  routes:
    filerestupload:
      path: /api/upload/**
      serviceId: FileRestPublicEndpoint
    elasticsearch:
      path: /proxy/elasticsearch/**
      url: ${elasticsearch.scheme}://${elasticsearch.hostname}:${elasticsearch.port}
    mongoexpress:
      path: /proxy/mongo/**
      url: http://${mongoexpress.host}:${mongoexpress.port}/proxy/mongo/
    virtuoso:
      path: /proxy/virtuoso/**
      url: ${virtuoso.scheme}://${virtuoso.hostname}:${virtuoso.port}/sparql
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  ribbon:
    eager-load:
      enabled: on
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000