zuul:
  routes:
    elasticsearch:
      path: /proxy/elasticsearch/**
      url: ${elasticsearch.scheme}://${elasticsearch.hostname}:${elasticsearch.port}
    virtuoso:
      path: /proxy/virtuoso/**
      url: ${virtuoso.scheme}://${virtuoso.hostname}:${virtuoso.port}