zuul:
  routes:
    filerestupload:
      path: /api/upload/**
      serviceId: FileRestPublicEndpoint
    elasticsearch:
      path: /proxy/elasticsearch/**
      url: ${elasticsearch.scheme}://${elasticsearch.hostname}:${elasticsearch.port}
    virtuoso:
      path: /proxy/virtuoso/**
      url: ${virtuoso.scheme}://${virtuoso.hostname}:${virtuoso.port}/sparql