kafka:
  dispatcher:
    mongodb-sink-topic-out: event-sink-mongodb-out
    rdf-sink-topic-out: event-sink-rdf-out
application:
  basePath: ${PROJECT_BASE_PATH:${java.io.tmpdir}/project-rest}
server:
  port: 0
spring:
  application:
    name: ProjectRestPublicEndpoint
  profiles:
    include: kafka, zookeeper, rest, mongodb, feign, logging
  kafka:
    template:
      default-topic: event-sink-rdf
  cache:
    cache-names: selectSparqlQuery, constructSparqlQuery, askSparqlQuery
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=1800s
