mongodb:
  database:
    name: ${spring.application.name}
application:
  basePath: ${PROJECT_BASE_PATH:${java.io.tmpdir}/project-rest}
spring:
  application:
    name: ProjectRestPublicEndpoint
  profiles:
    include: kafka, zookeeper, rest, mongodb, feign, logging
  kafka:
    template:
      default-topic: event-sink-rdf
  cache:
    cache-names: selectSparqlQuery, constructSparqlQuery, askSparqlQuery, queryTemplate
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=1800s
