application:
  basePath: ${PROJECT_BASE_PATH:${java.io.tmpdir}/shacl-rest}
server:
  port: 0
spring:
  application:
    name: ShaclRestPublicEndpoint
  profiles:
    include: kafka, zookeeper, rest, feign, logging
