kafka:
  listener:
    topics: event-sink-log
log:
  sink:
    index: logsink
spring:
  profiles:
    include: kafka, elasticsearch, logging
application:
  basePath: ${PROJECT_BASE_PATH:${java.io.tmpdir}/log-sink}
