kafka:
  listener:
    topics: event-sink-log
spring:
  main:
    web-application-type: none
  profiles:
    include: kafka, elasticsearch, logging
application:
  basePath: ${PROJECT_BASE_PATH:${java.io.tmpdir}/log-sink}
