out:
  topic: event-sink-log-out
log:
  sink:
    index: logsink
spring:
  profiles:
    include: kafka, elasticsearch, logging
  kafka:
    template:
      default-topic: event-sink-log
application:
  basePath: ${PROJECT_BASE_PATH:${java.io.tmpdir}/log-sink}