server:
  port: 8088
spring:
  application:
    name: RestPublicEndpoint
  profiles:
    include: kafka, sparql, elasticsearch, zuul, zookeeper, rest, mongoexpress, skosplay

elasticsearch:
  index: movies

