kafka:
  listener:
    topics: event-sink-mongodb

spring:
  main:
    web-application-type: none
  application:
    name: MongoDbSink
  profiles:
    include: kafka, mongodb, feign, logging

application:
  basePath: ${PROJECT_BASE_PATH:${java.io.tmpdir}/mongodb-sink}
