application:
  basePath: ${PROJECT_BASE_PATH:${java.io.tmpdir}/rest-gateway}
spring:
  application:
    name: RestPublicEndpoint
  profiles:
    include: sparql, elasticsearch, zuul, zookeeper, rest, rest-override, mongoexpress, logging, database, security
management:
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: GET
        allowed-headers: '*'
---
spring:
  profiles: rest-override
server:
  port: ${SERVER_PORT:8088}
