feign:
  httpclient:
    connection-timeout: 30000

endpoint:
  file:
    url: ${FILE_ENDPOINT_URL:http://localhost:8088/api/upload}
  project:
    url: ${PROJECT_ENDPOINT_URL:http://localhost:8088/api/project}
  shacl:
    url: ${PROJECT_ENDPOINT_URL:http://localhost:8088/api/shacl}