zuul:
  routes:
    filerestupload:
      path: /api/upload/**
      serviceId: FileRestPublicEndpoint
    projectrestupload:
      path: /api/project/**
      serviceId: ProjectRestPublicEndpoint
    elasticsearch:
      path: /proxy/elasticsearch/**
      url: ${elasticsearch.scheme}://${elasticsearch.hostname}:${elasticsearch.port}
    mongoexpress:
      path: /proxy/mongo/**
      url: http://${mongoexpress.host}:${mongoexpress.port}/proxy/mongo/
    sparql:
      path: /proxy/sparql/**
      url: ${sparql.endpoint.proxy.url}
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  ribbon:
    eager-load:
      enabled: on
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000