feign:
  httpclient:
    connection-timeout: 30000

endpoint:
  file:
    url: ${FILE_ENDPOINT_URL:http://192.168.99.102:8088/api/upload}
  project:
    url: ${PROJECT_ENDPOINT_URL:http://192.168.99.102:8088/api/project}