version: '3'

services:
  atrianglevirtuoso:
    restart: always
    container_name: virtuoso
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "https://www.artcoded.tech/default-graph"
      DBA_PASSWORD: "dba"
    volumes:
      - virtuoso-storage:/data
    ports:
      - "8890"
      - "1111"
    networks:
      atriangle:
        aliases:
          - virtuoso
  atriangleelasticsearch:
    restart: always
    container_name: atriangle_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    networks:
      atriangle:
        aliases:
          - elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms3072m -Xmx4196m"
      - "discovery.type=single-node"
    ports:
      - "9200"
      - "9300"
  atrianglezookeeper:
    restart: always
    image: zookeeper
    ports:
      - "2181"
    networks:
      atriangle:
        aliases:
          - zookeeper
  atrianglekafka:
    restart: always
    build: kafka-docker/.
    depends_on:
      - atrianglezookeeper
    ports:
      - "9092"
      - "9093"
    networks:
      atriangle:
        aliases:
          - kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  atriangleelasticsink:
    restart: always
    depends_on:
      - atriangleelasticsearch
      - atrianglekafka
    networks:
      atriangle:
        aliases:
          - elasticsink
    image: atriangle/elastic-sink
    environment:
      ELASTICSEARCH_HOSTNAME: "elasticsearch"
      KAFKA_BOOTSTRAP_SERVER: "kafka"
    volumes:
      - elastic-sink-storage:/app/user
  atrianglelogsink:
    restart: always
    depends_on:
      - atriangleelasticsearch
      - atrianglekafka
    networks:
      atriangle:
        aliases:
          - logsink
    image: atriangle/log-sink
    environment:
      ELASTICSEARCH_HOSTNAME: "elasticsearch"
      KAFKA_BOOTSTRAP_SERVER: "kafka"
    volumes:
      - log-sink-storage:/app/user
  atrianglerestsink:
    restart: always
    depends_on:
      - atrianglekafka
    networks:
      atriangle:
        aliases:
          - restsink
    image: atriangle/rest-sink
    environment:
      KAFKA_BOOTSTRAP_SERVER: "kafka"
    volumes:
      - rest-sink-storage:/app/user
  atrianglerdfsink:
    restart: always
    depends_on:
      - atrianglevirtuoso
      - atrianglekafka
    networks:
      atriangle:
        aliases:
          - rdfsink
    image: atriangle/rdf-sink
    environment:
      VIRTUOSO_HOSTNAME: "virtuoso"
      KAFKA_BOOTSTRAP_SERVER: "kafka"
    volumes:
      - rdf-sink-storage:/app/user
  atriangleeventdispatcher:
    depends_on:
      - atrianglekafka
    networks:
      atriangle:
        aliases:
          - eventdispatcher
    image: atriangle/event-dispatcher
    environment:
      KAFKA_BOOTSTRAP_SERVER: "kafka"
    volumes:
      - event-dispatcher-storage:/app/user
  atrianglerest:
    restart: always
    depends_on:
      - atrianglekafka
      - atrianglevirtuoso
      - atriangleelasticsearch
    networks:
      atriangle:
        aliases:
          - rest
    image: atriangle/rest
    ports:
      - "8088:8088"
    environment:
      ELASTICSEARCH_HOSTNAME: "elasticsearch"
      VIRTUOSO_HOSTNAME: "virtuoso"
      KAFKA_BOOTSTRAP_SERVER: "kafka"
      ZOOKEEPER_URL: "zookeeper:2181"
    volumes:
      - rest-storage:/app/user

volumes:
  virtuoso-storage:
  elastic-sink-storage:
  rdf-sink-storage:
  rest-sink-storage:
  log-sink-storage:
  event-dispatcher-storage:
  rest-storage:

networks:
  atriangle: