version: '3'

services:
  skosplaylocal:
    build: skosplay/.
    restart: always
    volumes:
      - skosplay-storage-local:/usr/app
    networks:
      atrianglelocal:
        aliases:
          - skosplaylocal
    ports:
      - "8080:8080"
  atriangleblazegraphlocal:
    build: blazegraph/2.1.5/.
    restart: always
    volumes:
      - blazegraph-storage-local:/usr/local
    networks:
      atrianglelocal:
        aliases:
          - blazegraph
    ports:
      - "8889:8080"
  atrianglemongolocal:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      atrianglelocal:
        aliases:
          - mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-storage:/data/db
  atrianglemongoexpresslocal:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_SITE_BASEURL: /proxy/mongo/
    ports:
      - "8081:8081"
    networks:
      atrianglelocal:
        aliases:
          - mongoexpress
  atriangleelasticsearchlocal:
    restart: always
    container_name: elasticsearch_local
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    networks:
      atrianglelocal:
        aliases:
          - elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms3072m -Xmx4196m"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
  atrianglezookeeperlocal:
    restart: always
    image: zookeeper
    ports:
      - "2181:2181"
    networks:
      atrianglelocal:
        aliases:
          - zookeeper
  atrianglekafkalocal:
    restart: always
    build: kafka-docker/.
    depends_on:
      - atrianglezookeeperlocal
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      atrianglelocal:
        aliases:
          - kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.102
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mongodb-storage:
  blazegraph-storage-local:
  skosplay-storage-local:

networks:
  atrianglelocal: