mongodb:
  database:
    name: ${spring.application.name}
application:
  basePath: ${UPLOAD_BASE_PATH:${java.io.tmpdir}/upload-rest}
  filePath: ${application.basePath}/uploads
spring:
  application:
    name: FileRestPublicEndpoint
  profiles:
    include: kafka, zookeeper, mongodb, rest, logging
