application:
  basePath: ${UPLOAD_BASE_PATH:${java.io.tmpdir}/upload-rest}
  filePath: ${application.basePath}/uploads
server:
  port: 0
spring:
  application:
    name: FileRestPublicEndpoint
  profiles:
    include: kafka, zookeeper, mongodb, rest, logging
