application:
  basePath: ${PROJECT_BASE_PATH:/tmp/project-rest} # todo do not forget to override on docker compose
server:
  port: 0
spring:
  application:
    name: ProjectRestPublicEndpoint
  profiles:
    include: kafka, zookeeper, rest, mongodb
  data:
    mongodb:
      host: ${MONGO_DB_HOST:192.168.99.101}
      port: ${MONGO_DB_PORT:27017}
      username: ${MONGO_DB_USERNAME:root}
      password: ${MONGO_DB_USERNAME:root}
      database: ${spring.application.name:DEFAULT_COLLECTION}
