kafka:
  listener:
    topics: event-sink-rdf
  dispatcher:
    mongodb-sink-topic: event-sink-mongodb
spring:
  profiles:
    include: kafka, feign, logging
  main:
    web-application-type: none

application:
  basePath: ${PROJECT_BASE_PATH:${java.io.tmpdir}/rdf-sink}
