kafka:
  listener:
    topics: event-sink-rdf
  dispatcher:
    mongodb-sink-topic: event-sink-mongodb
    rdf-sink-topic-out: event-sink-rdf-out
spring:
  profiles:
    include: kafka, feign, logging

application:
  basePath: ${PROJECT_BASE_PATH:${java.io.tmpdir}/rdf-sink}
