spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOST:192.168.99.101}
      port: ${MONGO_DB_PORT:27017}
      username: ${MONGO_DB_USERNAME:root}
      password: ${MONGO_DB_USERNAME:root}
      database: ${spring.application.name:DEFAULT_COLLECTION}