virtuoso:
  defaultGraph: https://www.artcoded.tech/default-graph
  hostname: 192.168.99.101
  password: dba
  port: 8890
  scheme: http
  sparql:
    endpoint:
      url: ${virtuoso.scheme}://${virtuoso.hostname}:${virtuoso.port}/sparql
  username: dba