zuul:
  routes:
    xls2rdf:
      path: /api/xls2rdf/**
      serviceId: Xls2RdfRestPublicEndpoint
    sparqlrest:
      path: /api/sparql/**
      serviceId: SparqlRestPublicEndpoint
    filerestupload:
      path: /api/upload/**
      serviceId: FileRestPublicEndpoint
    projectrest:
      path: /api/project/**
      serviceId: ProjectRestPublicEndpoint
    elasticrest:
      path: /api/elastic/**
      serviceId: ElasticRestPublicEndpoint
    mongodbrest:
      path: /api/mongodb/**
      serviceId: MongoDbRestPublicEndpoint
    shaclrest:
      path: /api/shacl/**
      serviceId: ShaclRestPublicEndpoint
    elasticsearch:
      path: /proxy/elasticsearch/**
      url: ${elasticsearch.scheme}://${elasticsearch.hostname}:${elasticsearch.port}
    mongoexpress:
      path: /proxy/mongo/**
      url: http://${mongoexpress.host}:${mongoexpress.port}/proxy/mongo/
    sparql:
      path: /proxy/sparql-endpoint/**
      url: ${sparql.endpoint.proxy.url}
  host:
    connect-timeout-millis: 45000
    socket-timeout-millis: 45000
  ribbon:
    eager-load:
      enabled: on
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ConnectTimeout: 45000
  ReadTimeout: 45000
