feign:
  httpclient:
    connection-timeout: 30000

endpoint:
  file:
    url: ${FILE_ENDPOINT_URL:http://localhost:8088/api/upload}
  project:
    url: ${PROJECT_ENDPOINT_URL:http://localhost:8088/api/project}
  shacl:
    url: ${SHACL_ENDPOINT_URL:http://localhost:8088/api/shacl}
  skosplay:
    url: ${XLS2RDF_ENDPOINT_URL:http://localhost:8088/api/xls2rdf}