feign:
  httpclient:
    connection-timeout: 45000

endpoint:
  sparql:
    url: ${SPARQL_ENDPOINT_URL:http://localhost:8088/api/sparql}
  file:
    url: ${FILE_ENDPOINT_URL:http://localhost:8088/api/upload}
  project:
    url: ${PROJECT_ENDPOINT_URL:http://localhost:8088/api/project}
  shacl:
    url: ${SHACL_ENDPOINT_URL:http://localhost:8088/api/shacl}
  elastic:
    url: ${ELASTIC_ENDPOINT_URL:http://localhost:8088/api/elastic}
  skosplay:
    url: ${XLS2RDF_ENDPOINT_URL:http://localhost:8088/api/xls2rdf}
