spring:
  resources:
    add-mappings: true
  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE:500MB}
      max-file-size:  ${MAX_FILE_SIZE:500MB}

management:
  health:
    mail:
      enabled: false
    elasticsearch:
      enabled: false
    solr:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: ${ACTUATOR_ENABLED:true}
  endpoint:
    logfile:
      external-file: ${logging.file.path}
