server:
  port: 8088
spring:
  application:
    name: RestPublicEndpoint
  profiles:
    include: kafka, sparql, elasticsearch, zuul, zookeeper, rest, mongoexpress
  kafka:
    template:
      default-topic: event-sink-rest

elasticsearch:
  index: movies

