event:
  dispatcher:
    elastic-sink-topic: event-sink-elastic
    mongodb-sink-topic: event-sink-mongodb
    rdf-sink-topic: event-sink-rdf
spring:
  profiles:
    include: kafka
  kafka:
    template:
      default-topic: event-dispatcher
