application:
  basePath: ${UPLOAD_BASE_PATH:/tmp/upload-rest} # todo do not forget to override on docker compose
  filePath: ${application.basePath}/uploads
server:
  port: 0
spring:
  application:
    name: FileRestPublicEndpoint
  profiles:
    include: kafka, zookeeper, database, rest
