kafka:
  listener:
    topics: event-sink-elastic
  dispatcher:
    elastic-sink-topic-out: event-sink-elastic-out
application:
  basePath: ${PROJECT_BASE_PATH:${java.io.tmpdir}/elastic-sink}
spring:
  profiles:
    include: kafka, elasticsearch, feign, logging
