application:
  basePath: ${PROJECT_BASE_PATH:${java.io.tmpdir}/mongodb-rest}
server:
  port: 0
spring:
  application:
    name: MongoDbRestPublicEndpoint
  profiles:
    include: kafka, zookeeper, rest, feign, logging, mongodb
